import type { RepoSettingsDialogController } from "@/components/use-repo-settings-dialog-controller";

export type RepoSettingsDisplayController = Pick<
  RepoSettingsDialogController,
  | "addRepositoryTags"
  | "commitRepositoryTagInput"
  | "displayName"
  | "displayNameId"
  | "draggedRepositoryTagIndex"
  | "effectiveReleaseSelectionStrategy"
  | "handleRepositoryTagLostPointerCapture"
  | "handleRepositoryTagPointerCancel"
  | "handleRepositoryTagPointerDown"
  | "handleRepositoryTagPointerEnd"
  | "handleRepositoryTagPointerMove"
  | "hasDisplayNameError"
  | "isOnline"
  | "isPinned"
  | "isPinnedId"
  | "isRtl"
  | "releaseSelectionStrategy"
  | "releaseSelectionStrategyId"
  | "removeRepositoryTag"
  | "reorderRepositoryTag"
  | "repositoryTagDragSize"
  | "repositoryTagDropIndex"
  | "repositoryTagErrorMessage"
  | "repositoryTagInput"
  | "repositoryTagListRef"
  | "repositoryTagOrderAnnouncement"
  | "repositoryTagSuggestions"
  | "repositoryTags"
  | "repositoryTagsId"
  | "requestImmediateSave"
  | "setDisplayName"
  | "setIsPinned"
  | "setReleaseSelectionStrategy"
  | "setRepositoryTagError"
  | "setRepositoryTagInput"
  | "setVersionTagPattern"
  | "useDefaultVersionTagPattern"
  | "useGlobalReleaseSelection"
  | "versionTagPattern"
  | "versionTagPatternError"
  | "versionTagPatternId"
>;

export type RepoSettingsFilterController = Pick<
  RepoSettingsDialogController,
  | "customPreReleaseMarkers"
  | "customPreReleaseMarkersId"
  | "draftId"
  | "effectivePreReleaseSubChannels"
  | "excludeRegex"
  | "excludeRegexError"
  | "excludeRegexId"
  | "handleChannelChange"
  | "handleDeselectAllPreRelease"
  | "handlePreReleaseSubChannelChange"
  | "handleResetFilters"
  | "handleSelectAllPreRelease"
  | "includeRegex"
  | "includeRegexError"
  | "includeRegexId"
  | "invalidCustomPreReleaseMarkers"
  | "isDraftChecked"
  | "isOnline"
  | "isPreReleaseChecked"
  | "isStableChecked"
  | "prereleaseId"
  | "prereleaseSubChannelBaseId"
  | "setCustomPreReleaseMarkers"
  | "setExcludeRegex"
  | "setIncludeRegex"
  | "setUseGlobalCustomPreReleaseMarkers"
  | "stableId"
  | "useGlobalChannels"
  | "useGlobalCustomPreReleaseMarkers"
  | "useGlobalCustomPreReleaseMarkersId"
>;

export type RepoSettingsAutomationController = Pick<
  RepoSettingsDialogController,
  | "automationMode"
  | "cacheDays"
  | "cacheDaysId"
  | "cacheHours"
  | "cacheHoursId"
  | "cacheMinutes"
  | "cacheMinutesId"
  | "cacheOverrideId"
  | "cronError"
  | "cronExpression"
  | "cronExpressionId"
  | "cronHourId"
  | "cronMinuteId"
  | "cronPeriodId"
  | "cronPreset"
  | "cronPresetId"
  | "cronTime"
  | "cronWeekday"
  | "cronWeekdayId"
  | "handleResetAutomation"
  | "intervalDays"
  | "intervalDaysId"
  | "intervalError"
  | "intervalHours"
  | "intervalHoursId"
  | "intervalMinutes"
  | "intervalMinutesId"
  | "isCacheInvalid"
  | "isOnline"
  | "refreshModeId"
  | "requestImmediateSave"
  | "setAutomationMode"
  | "setCacheDays"
  | "setCacheHours"
  | "setCacheMinutes"
  | "setCronExpression"
  | "setCronPreset"
  | "setCronTime"
  | "setCronWeekday"
  | "setIntervalDays"
  | "setIntervalHours"
  | "setIntervalMinutes"
  | "setUseCustomCache"
  | "useCustomCache"
>;

export type RepoSettingsDeliveryController = Pick<
  RepoSettingsDialogController,
  | "appriseFormat"
  | "appriseFormatId"
  | "appriseTags"
  | "appriseTagsId"
  | "isOnline"
  | "releasesPerPage"
  | "releasesPerPageError"
  | "releasesPerPageId"
  | "requestImmediateSave"
  | "setAppriseFormat"
  | "setAppriseTags"
  | "setReleasesPerPage"
  | "useGlobalAppriseFormat"
  | "useGlobalAppriseTags"
  | "useGlobalReleasesPerPage"
>;
